// MOBILE ROBOT PROPERTIES
#define num_ROBOT_WHEELS        4

// MECANUM WHEEL PROPERTIES
#define ALPHA_DEG	            45

// ENCODER PROPERTIES
#define	ZERO_ENC	            0
#define PULS4REV	            1320

// STATE MACHINE PROPERTIES
#define UPDATE_INTERVAL         1
