// MOBILE ROBOT PROPERTIES
#define num_ROBOT_WHEELS        2

// MECANUM WHEEL PROPERTIES
#define ALPHA_DEG	            45
#define ROTATION_PWM            100     //THE PWM MOTOR THAT MOTORS ARE SET WHEN PURE ROTATION IS DESIRED

// ENCODER PROPERTIES
#define	ZERO_ENC	            0
#define PULS4REV	            1320

// STATE MACHINE PROPERTIES
#define UPDATE_INTERVAL         20
